#!/bin/bash

if [ ! -e "/usr/local/bin/python3.13" ]; then
    echo "python version is not supported"
    exit 1
fi

if [[ "$(systemctl is-active home-assistant.service)" == "active" ]]; then
    echo "Stopping home-assistant.service"
    systemctl stop home-assistant.service
fi

if [[ "$(systemctl is-active matter-server.service)" == "active" ]]; then
    echo "Stopping matter-server.service"
    systemctl stop matter-server.service
fi

