#!/bin/bash

[ -f "/usr/bin/python3.13" ] || \
[ -f "/usr/local/bin/python3.13" ] || \
[ -f "/usr/local/python3/bin/python3.13" ] || {
    echo "Error: Python 3.13 not found in any of:" >&2
    echo "  /usr/bin/python3.13" >&2
    echo "  /usr/local/bin/python3.13" >&2
    echo "  /usr/local/python3/bin/python3.13" >&2
    exit 1
}

if [[ "$(systemctl is-active home-assistant.service)" == "active" ]]; then
    echo "Stopping home-assistant.service"
    systemctl stop home-assistant.service
fi

if [[ "$(systemctl is-active matter-server.service)" == "active" ]]; then
    echo "Stopping matter-server.service"
    systemctl stop matter-server.service
fi

