#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
	rm -rf /var/lib/homeassistant/zha.conf
	rm -rf /var/lib/homeassistant/zha.conf.bak

	chmod +x /usr/local/bin/zigpy_help.sh
	
	# Check if the architecture is aarch64
	if [ "$(uname -m)" = "aarch64" ]; then
		SCRIPT_PATH="/usr/local/thirdreality/zigpy_tools/bin/zigpy_hw_info.sh"

		# Check if the script exists
		if [ -f "$SCRIPT_PATH" ]; then
			# Execute the script
			chmod +x "$SCRIPT_PATH"
			if [ -e "/var/lib/homeassistant/homeassistant/configuration.yaml" ]; then
				"$SCRIPT_PATH" > /dev/null 2>&1 || {
					echo "[WARN] zigpy_hw_info.sh failed, but continuing..." 
				}
			fi
		else
			echo "Warn: Script $SCRIPT_PATH not found."
		fi
	fi
fi

exit 0
