#!/bin/bash

set -e

PACKAGE="thirdreality-zigpy-tools"
if dpkg -l | grep -q "^ii  $PACKAGE "; then
  echo "[Warn] $PACKAGE conflict, you should remove $PACKAGE first."
  exit 1
fi


TARGET_DIR="/var/lib/homeassistant"
if [ -d "$TARGET_DIR" ]; then
    rm -rf "$TARGET_DIR" || true
fi

