#!/bin/bash
set -e

INFRA_IF_NAME="wlan0"
readonly INFRA_IF_NAME

SYSCTL_ACCEPT_RA_FILE="/etc/sysctl.d/60-otbr-accept-ra.conf"
readonly SYSCTL_ACCEPT_RA_FILE

SYSCTL_IP_FORWARD_FILE="/etc/sysctl.d/60-otbr-ip-forward.conf"
readonly SYSCTL_IP_FORWARD_FILE

accept_ra_enable()
{
    echo 2 | tee /proc/sys/net/ipv6/conf/"${INFRA_IF_NAME}"/accept_ra || die 'Failed to enable IPv6 RA!'
    echo 64 | tee /proc/sys/net/ipv6/conf/"${INFRA_IF_NAME}"/accept_ra_rt_info_max_plen || die 'Failed to enable IPv6 RIO!'
}

ipforward_enable()
{
    echo 1 | tee /proc/sys/net/ipv6/conf/all/forwarding || die 'Failed to enable IPv6 forwarding!'
    echo 1 | tee /proc/sys/net/ipv4/ip_forward || die 'Failed to enable IPv4 forwarding!'
}

#/etc/sysctl.conf
#/etc/iproute2/rt_tables
rt_tables_install()
{
    sed -i.bak '/88\s\+openthread/d' /etc/iproute2/rt_tables

    echo "88 openthread" >>/etc/iproute2/rt_tables

    echo "" >>/etc/sysctl.conf
    echo "# OpenThread configuration" >>/etc/sysctl.conf
    echo "net.core.optmem_max=65536" >>/etc/sysctl.conf
    sysctl -p /etc/sysctl.conf
}

# 检查是安装还是升级
if [ "$1" = "configure" ]; then

	if [ -f "/usr/lib/libdns_sd.so.1" ]; then
		ln -s -f /usr/lib/libdns_sd.so.1 /usr/lib/libdns_sd.so
	fi 
	
	if [ -f "/lib/libnss_mdns-0.2.so" ]	; then
		chmod 444 /lib/libnss_mdns-0.2.so
		ln -s -f /lib/libnss_mdns-0.2.so /lib/libnss_mdns.so.2
	fi

	if [ -f "/etc/init.d/mdns" ]; then
		chmod ugo+x /etc/init.d/mdns
		ln -s -f /etc/init.d/mdns /etc/rc2.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc3.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc4.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc5.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc0.d/K16mdns
		ln -s -f /etc/init.d/mdns /etc/rc6.d/K16mdns
	fi

	if [ -f "/etc/nss_mdns.conf" ]; then
		chmod 444 /etc/nss_mdns.conf
	fi
	
	if [ -f "/etc/init.d/otbr-firewall" ]; then
		chmod a+x /etc/init.d/otbr-firewall
		/usr/bin/systemctl enable otbr-firewall
		/usr/bin/systemctl start otbr-firewall
	fi

	# accept_ra_install
    accept_ra_enable

	# ipforward_install
    ipforward_enable

	rt_tables_install

	/usr/bin/systemctl reload dbus
	/usr/bin/systemctl daemon-reload

    /usr/bin/systemctl enable otbr-agent || true
    /usr/bin/systemctl is-enabled otbr-agent || die "Failed to enable otbr-agent!"

	echo "Success"
fi

exit 0

