#!/bin/bash
set -e

INFRA_IF_NAME="wlan0"
readonly INFRA_IF_NAME

SYSCTL_ACCEPT_RA_FILE="/etc/sysctl.d/60-otbr-accept-ra.conf"
readonly SYSCTL_ACCEPT_RA_FILE

SYSCTL_IP_FORWARD_FILE="/etc/sysctl.d/60-otbr-ip-forward.conf"
readonly SYSCTL_IP_FORWARD_FILE

accept_ra_enable()
{
    echo 2 | tee /proc/sys/net/ipv6/conf/"${INFRA_IF_NAME}"/accept_ra || die 'Failed to enable IPv6 RA!'
    echo 64 | tee /proc/sys/net/ipv6/conf/"${INFRA_IF_NAME}"/accept_ra_rt_info_max_plen || die 'Failed to enable IPv6 RIO!'
}

ipforward_enable()
{
    echo 1 | tee /proc/sys/net/ipv6/conf/all/forwarding || die 'Failed to enable IPv6 forwarding!'
    echo 1 | tee /proc/sys/net/ipv4/ip_forward || die 'Failed to enable IPv4 forwarding!'
}

#/etc/sysctl.conf
#/etc/iproute2/rt_tables
rt_tables_install()
{
    sed -i.bak '/88\s\+openthread/d' /etc/iproute2/rt_tables

    echo "88 openthread" >>/etc/iproute2/rt_tables

    echo "" >>/etc/sysctl.conf
    echo "# OpenThread configuration" >>/etc/sysctl.conf
    echo "net.core.optmem_max=65536" >>/etc/sysctl.conf
    sysctl -p /etc/sysctl.conf
}

add_open_thread_entry_to_config() {
    local config_file="/var/lib/homeassistant/homeassistant/.storage/core.config_entries"
    local new_entry='{"created_at":"2025-01-01T07:18:49.447764+00:00","data":{"url":"http://localhost:8081"},"disabled_by":null,"discovery_keys":{},"domain":"otbr","entry_id":"01JVKPHNB75FCSNFYPTT7KMVCM","minor_version":1,"modified_at":"2025-01-01T07:18:49.447801+00:00","options":{},"pref_disable_new_entities":false,"pref_disable_polling":false,"source":"user","subentries":[],"title":"Open Thread Border Router","unique_id":"5e339577507d32ff95d5817d60f8d183","version":1}'
    if [ -f "$config_file" ]; then
        # Check if the "domain": "otbr" already exists
        if ! jq -e '.data.entries[] | select(.domain == "otbr")' "$config_file" > /dev/null; then
            # Use jq to add new entry to the entries list
            temp_file=$(mktemp)
            jq --argjson new_entry "$new_entry" '.data.entries += [$new_entry]' "$config_file" > "$temp_file" && mv "$temp_file" "$config_file"
            echo "New entry added."
        else
            echo "Entry with domain 'otbr' already exists. No changes made."
        fi
    else
        echo "Error: Configuration file $config_file not found"
    fi
}


# 检查是安装还是升级
if [ "$1" = "configure" ]; then
	
	mkdir -p /var/lib/thread

	if [ -f "/usr/lib/libdns_sd.so.1" ]; then
		ln -s -f /usr/lib/libdns_sd.so.1 /usr/lib/libdns_sd.so
	fi 
	
	if [ -f "/lib/libnss_mdns-0.2.so" ]	; then
		chmod 444 /lib/libnss_mdns-0.2.so
		ln -s -f /lib/libnss_mdns-0.2.so /lib/libnss_mdns.so.2
	fi

	if [ -f "/etc/init.d/mdns" ]; then
		chmod ugo+x /etc/init.d/mdns
		ln -s -f /etc/init.d/mdns /etc/rc2.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc3.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc4.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc5.d/S52mdns
		ln -s -f /etc/init.d/mdns /etc/rc0.d/K16mdns
		ln -s -f /etc/init.d/mdns /etc/rc6.d/K16mdns
	fi

	if [ -f "/etc/nss_mdns.conf" ]; then
		chmod 444 /etc/nss_mdns.conf
	fi
	
	if [ -f "/etc/init.d/otbr-firewall" ]; then
		chmod a+x /etc/init.d/otbr-firewall
		/usr/bin/systemctl enable otbr-firewall
		/usr/bin/systemctl start otbr-firewall
	fi

	# accept_ra_install
    accept_ra_enable

	# ipforward_install
    ipforward_enable

	rt_tables_install

	chmod +x /usr/lib/thirdreality/hubv3-otbr-agent.sh
	/usr/bin/systemctl enable hubv3-otbr-agent.service
	/usr/bin/systemctl disable otbr-agent || true
	/usr/bin/systemctl reload dbus
	/usr/bin/systemctl daemon-reload

	# 检查 GPIO pin 0, 27 的状态
    if gpioget 0 27; then
		echo "Info: Thread Device is found."

		msg=$(iw dev wlan0 link 2>&1)
		if echo "$msg" | grep -q "Connected"; then
			/usr/bin/systemctl start otbr-agent || true
		fi

		if [ -e "/usr/local/bin/supervisor" ]; then
			/usr/local/bin/supervisor thread enable
		fi

		# 如果Home Assistant正在运行，需要停止服务，然后更新配置，再恢复服务
		if [[ "$(/usr/bin/systemctl is-active home-assistant.service)" == "active" ]]; then
			echo "Stopping home-assistant.service"
			/usr/bin/systemctl stop home-assistant.service

			sync
			add_open_thread_entry_to_config
			sync

			echo "Restore home-assistant.service"
			/usr/bin/systemctl start home-assistant.service
		else
			echo "Skipping home-assistant.service"
			add_open_thread_entry_to_config
			sync
		fi		
    else
		echo "Warning: Thread Device is not found !!!"
        /usr/bin/systemctl stop otbr-agent || true
    fi

	echo "Success"
fi

