#!/bin/bash
set -e

FIREWALL_SERVICE=/etc/init.d/otbr-firewall

SYSCTL_ACCEPT_RA_FILE="/etc/sysctl.d/60-otbr-accept-ra.conf"
SYSCTL_IP_FORWARD_FILE="/etc/sysctl.d/60-otbr-ip-forward.conf"

# 停止服务
if [ "$1" = "remove" ]; then
    echo "Stopping otbr-web/otbr-agent/otbr-firewall services ..."

    /usr/bin/systemctl stop otbr-web || true
    /usr/bin/systemctl stop otbr-agent || true

    /usr/bin/systemctl disable otbr-web || true
    /usr/bin/systemctl disable otbr-agent || true

    killall otbr-web otbr-agent || true

    /usr/bin/systemctl stop otbr-firewall || true
    /usr/bin/systemctl disable otbr-firewall || true

    if [ -f "/usr/sbin/update-rc.d" ]; then
        /usr/sbin/update-rc.d otbr-firewall remove || true
    fi

    /usr/bin/systemctl daemon-reload

    test ! -f ${FIREWALL_SERVICE} || rm ${FIREWALL_SERVICE}

    test ! -f ${SYSCTL_ACCEPT_RA_FILE} || rm -v ${SYSCTL_ACCEPT_RA_FILE}
    test ! -f ${SYSCTL_IP_FORWARD_FILE} || rm -v ${SYSCTL_IP_FORWARD_FILE}

    echo "Restoring /etc/iproute2/rt_tables ..."
    sed -i.bak '/88\s\+openthread/d' /etc/iproute2/rt_tables

    rm -rf /lib/libnss_mdns.so.2
    rm -rf /usr/lib/libdns_sd.so

    rm -rf /etc/rc2.d/S52mdns 
	rm -rf /etc/rc2.d/S52mdns
	rm -rf /etc/rc3.d/S52mdns
	rm -rf /etc/rc4.d/S52mdns
	rm -rf /etc/rc5.d/S52mdns
	rm -rf /etc/rc0.d/K16mdns
	rm -rf /etc/rc6.d/K16mdns

    sysctl -p /etc/sysctl.conf

    rm -rf /var/lib/thread

    echo "Remove success."
fi

exit 0
