#!/bin/bash
set -e

# 停止服务
if [ "$1" = "remove" ]; then

    rm -rf /var/lib/homeassistant/supervisor-version
    rm -rf /var/lib/homeassistant/supdater.json
    rm -rf /var/lib/homeassistant/ssl
    rm -rf /var/lib/homeassistant/services.json
    rm -rf /var/lib/homeassistant/observer.json
    rm -rf /var/lib/homeassistant/multicast.json
    rm -rf /var/lib/homeassistant/homeassistant.json
    rm -rf /var/lib/homeassistant/emergency
    rm -rf /var/lib/homeassistant/dns
    rm -rf /var/lib/homeassistant/dns.json
    rm -rf /var/lib/homeassistant/core

    rm -rf /var/lib/homeassistant/config.json
    rm -rf /var/lib/homeassistant/cli.json
    rm -rf /var/lib/homeassistant/audio.json
    rm -rf /var/lib/homeassistant/audio
    rm -rf /var/lib/homeassistant/addons.json

	rm -rf /var/lib/homeassistant/.mounts_credentials

    rm -rf /var/lib/homeassistant/homeassistant/.HA_VERSION
    rm -rf /var/lib/homeassistant/homeassistant/home-assistant.log*
    rm -rf /var/lib/homeassistant/homeassistant/.storage/core.config
    rm -rf /var/lib/homeassistant/homeassistant/.storage/core.analytics

    rm -rf /var/lib/homeassistant/
    mkdir -p /var/lib/homeassistant/
    
    echo "Remove success."
fi

exit 0
